version: '3.4'

services:
  dashboard.api:
    image: milenaramiro/api-dashboard-fmd
    build:
      context: .
      dockerfile: src/Dashboard.Api/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"