version: '3.4'

services:
  dashboard.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "44378:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db 
    networks:
      - api-network
  db:
    container_name: dbDashboardApp
    environment:
        SA_PASSWORD: "@FMD2021"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - C:\MSSQL\BACKUP\KEEP:/var/opt/mssql/backups   
    networks:
      - api-network

  networks:
    api-network:
      driver: bridge
  